chris2511/xca

- lang/fr.po
Hi Christian,
Here is the new french translation for 2.0.0.
The legacy db import problem I told you by mail came from an installation path problem (conflicted with the system installation of XCA): it seems executing xca from the build directory without installing it if you have a system install of a previous version leads in run-time problems.
I also played with a MariaDB database: works well, nice job :-)
May I suggest you to implement a table/view name prefix within the external DB? This would allow resolving conflicts with use of the same DB by another application, and storing more than a single XCA DB into the same external DB.
Cheers,
Patrick
> Update french translation

- lib/db_temp.cpp
[lib/db_temp.cpp:104] -> [lib/db_temp.cpp:103]: (warning) Either the condition 'if(temp)' is redundant or there is possible null pointer dereference: temp.
> resolve possible null pointer dereference

- lib/ipvalidator.h
I'm maintaining the FreeBSD port of xca.
The latest version requires the attached patch to successfully compile on FreeBSD.
I included this patch in the ports collection.
Could this change be merged?
> Add includes required in FreeBSD to use in6_addr, AF_INET and AF_INET6.

- lib/db.cpp
- lib/exception.h
- lib/pkcs11_lib.h
- lib/pki_key.cpp
- lib/x509rev.h
Hi Christian,
This PR suppresses new gcc warnings. See commit comments for details.
There are still deprecated declaration warnings (using Qt 5.13). However fixing them requires to know which minimum version and release of Qt you would like to support:
- `QListWidget::isItemSelected()`/`QListWidget::setItemSelected()` should be replaced by `QListWidgetItem::isSelected()`/`QListWidgetItem::setSelected()`. The latters are only available since Qt 4.2.
- `QFontMetrics::width()` should be replaced by `QFontMetrics::horizontalAdvance()`. Available since Qt 5.11.
- `QSqlError::setDriverText()` should be replaced by `QSqlError` constructor. The signature of this constructor (and associated methods) are not the same in Qt 4 and Qt 5.
> Resolve gcc 9/10 new warnings.

- .travis.yml
- Dockerfile
- INSTALL.docker
This feature provides the following changes:
* adds a Dockerfile to build against specified versions of openssl
* enables travis matrix build
To build the container use
docker build --rm --build-arg USER_ID=`id -u` --tag xca .
To run xca use
docker run --rm -it --user `id -u` --network=host \
-e DISPLAY=$DISPLAY -e "QT_X11_NO_MITSHM=1" xca
Once travis is enabled, matrix build is provided. You will find an example at https://travis-ci.org/falk-werner/xca.  You might also want to add a badge to your README.md for build status. An example is provided at https://github.com/falk-werner/xca/tree/travis_badge.
> Feature: Provide docker container for XCA

- .gitignore
- misc/.gitignore
These are generated files, or ones that are potentially generated.
If you run `./configure -C` it'll generate config.cache
> Fix missing gitignore entries

- configure.ac
Some distributions use the autoheader command to generate and
overwrite the local.h file.
In contrast to autoconf, autoheader insists on the "description"
argument in AC_DEFINE_UNQUOTED(), so add it.
> Close #213: configure.ac: add description to AC_DEFINE_UNQUOTED

- INSTALL.mac
- configure.ac
These patches contain tweaks that simplify compiling xca on M1 with Big Sur. If homebrew and the xca build dependencies are installed and the xca code resides on a case-sensitive volume, builds can be performed using these commands:
```
./bootstrap
./configure
make
```
Related to #247
> Fix M1/Big Sur build

- lib/db_x509.cpp
- ui/CertExtend.ui
Hi, @chris2511 
I've added the checkbox into the certificate renewal UI. It allows deleting the old certificate while renewing it. Tested on my temporary db, works fine.
I also unchecked by-default the revoke-checkbox. My reasoning is that most of the time when one renews a certificate, its lifetime and subsequently validity are prolonged, therefore there is no need to revoke the old one as it is as trustworty as the new one. Apart from that, honestly saying I'm tired of always disabling this checkbox.
> Replace certificate while renewing

- widgets/TempTreeView.cpp
Call to temps may return nullptr if dynamic_cast fail to
cast pointer to db_temp* type, so we check that pointer is not null before using it.
> Fix possible null pointer dereference

- widgets/MainWindow.h
Method event can get called with QChildEvent instead of
QHelpEvent.
So we postpone cast after test for correct QHelpEvent condition.
> Fix wrong pointer type casting

- lib/pki_evp.cpp
Bug was introduced in [commit](https://github.com/chris2511/xca/commit/be1a44d0a8529e18807c6ca2b784c41ca0787647)
In old version for encryption always used EVP_aes_256_cbc():
``` C++
PEM_write_bio_PrivateKey(b, pkey, EVP_aes_256_cbc(),
```
In current version it always NULL:
``` C++
PEM_write_bio_PrivateKey(b, pkey, NULL,
```
This mr fix this by using value proper local variable.
> Enables usage of aes_256_cbc for private key export

- widgets/XcaDialog.cpp
Before that "" was concatenated with second element so each
call by index to that array would be off by 1.
So, for example instead of ":certImg", ":csrImg" - was used.
> Add missing comma between two image names

- lib/opensc-pkcs11.h
- lib/pkcs11.cpp
- lib/pki_scard.cpp
What works:
- Importing ED25519 Signature key from Yubikey token (OpenSC with openpgp driver, key generated via gpg)
- Creating self-signed certificate for CA, for Signature key from card
- Signing Certificates using new CA
I haven't tested other features, e.g. storing new certificate on card, so, they're probably broken
> Support importing ED25519 keys and signing with them, using PKCS#11 tokens

- doc/CMakeLists.txt
Lets packagers specify it instead of assuming it'll always be `<DATADIR>/doc` (e.g. `/usr/share/doc`).
> Use CMAKE_INSTALL_DOCDIR for docs location

- doc/rst/step-by-step.rst
When I followed the step-by-step documentation for the first time, I was confused at first by the New Certificate button being greyed out.
This commit adds a section which explains creating the database before creating a certificate.
> In the documention mention creating a datatbase

- lib/digest.cpp
It's pretty dumb workaround, but I tried to find the proper place, where this openssl error is raised, and failed.
> Fix #321 - decryptKey shows OpenSSL error, which were raised before

- lib/arguments.cpp
Expected CLI option arguments weren't passed to the QCommandLineOption constructor.
> Fix command line parsing

- lib/db_x509.cpp
- lib/pki_pkcs12.cpp
- lib/pki_pkcs12.h
- lib/settings.cpp
- ui/Options.ui
- widgets/CMakeLists.txt
- widgets/Options.cpp
- widgets/pkcs12EncBox.cpp
- widgets/pkcs12EncBox.h
This pull request adds the ability to configure the encryption algorithm used for cert and key encryption in a PKCS12 container.
According to PKCS5 v2.0, the AES-256-CBC algorithm is not allowed as an encryption scheme. It has been added in v2.1. But there are legacy systems such as Android, which are not capable of decrypting such a PKCS12 container. The code which has been present before these changes used PDE-3Key-3DES for the cert encryption, but the default in openssl (AES-256-CBC) for key encryption. This merge request sets both schemes to the same value, so if 3DES is selected in the options, then both key and cert get encrypted that way. By doing that importing a PKCS12 file on Android works.
> PKCS12 encryption algorithm setting

- lang/xca_pt_BR.ts
Fix typos, changed terms to it's more common use and fixed a bug into time/date into "Subject" tab.
> Update Portuguese Brazil Translation

- lib/db_base.cpp
This was bugging me.
| Before:      | After: |
| ----------- | ----------- |
| ![VAlignTop](https://github.com/chris2511/xca/assets/1297574/adceac42-0831-414a-bbe8-fe7f82c71281) | ![VAlignCenter](https://github.com/chris2511/xca/assets/1297574/e284dc8c-16e6-4a59-b087-9e00700e0e6a) |
P.S.: Thank you for this great tool that keeps me away from the abomination called openssl.
> Fix vertical text alignment in the tree views

- lib/db_x509.cpp
Hi Christian,
There has been a Fedora BZ report about an xca 2.5.0 crash: https://bugzilla.redhat.com/show_bug.cgi?id=2259477
I presumed commit https://github.com/chris2511/xca/commit/43e1b336d23e7512b246da142c78307baad4cbff would do the trick, but this is not sufficient.
Issue https://github.com/chris2511/xca/issues/493 would probably be fixed with this PR.
See the commit message for an explanation.
Cheers,
Patrick
> Fix a use-after-free crash

- Dockerfile
- INSTALL.docker
- misc/docker_start.sh
I have an use case with different users connect to a virtual machine with SSH and X-forwarding runnig XCA in Docker.
This PR introduces a small fix to the Dockerfile (since build was broken), as well as a change to allow controlling the userid XCA runs at container start time instead of build time. This enables different users to run the same container image. Also documentation is adapted to reflect these changes. Additionally, documentations points out how to circumvent issues regarding OpenGL, when running with X-forwarding.
> Dockerimage

- test/CMakeLists.txt
Added Pthread link flag to the test Cmakelist based on @chris2511 advise.
> #550: Fix compiling tests issue by providing -pthread link flag.

- lib/pki_evp.cpp
Resolves a few issues in the binary format of exported OpenSSH Private Key files, namely:
- The nonce was generated as a single 64bit random string instead of a 32bit string repeated twice.
- Null comment was omitted
- Padding was omitted
After implementing these changes and building XCA, I was able to confirm ED25519 keys are now working with OpenSSH:
fixes #658
> Fixes Broken ED25519 OpenSSH Private Key Exports
