lang/xca_hr.ts

Hi Christian,
Please find new Croatian localisation for XCA 2.0.0
Regards,
Nevenko

Updated croatian TS file

---

lang/fr.po

Update french translation

---

widgets/NewKey.cpp

I've verified this generates correct and working keys.

Allow for generating keys of 8192 bits in size

---

lang/Makefile
lang/xca_pt_BR.ts
widgets/MW_menu.cpp

Hello Christian Hohnstädt,
here is an initial part of the translation into the Portuguese language of Brazil.

Add Portuguese language of Brazil

---

lang/xca_pt_BR.ts

Update in portuguese language in brazil

---

lang/xca_zh.ts
widgets/MW_help.cpp

Hi,
The translation work in simplified chinese has been completed, please merge to the mainline, thank for your help!
xczh

Add simplified chinese translation file

---

lang/xca_es.ts

Updated spanish traslation to the lastest version.

Update spanish traslation

---

INSTALL
Local.mak.in
Makefile
doc/Makefile
img/Makefile
lang/Makefile
misc/Makefile

https://www.gnu.org/software/automake/manual/html_node/DESTDIR.html

Use standard GNU variables during installation

---

lang/fr.po

Hi Christian,
Here is the updated french translation requested.
Cheers,
Patrick

French translation for 2.3.0.

---

lang/xca_nl.ts
misc/xca.desktop

Dutch translation for 2.3.0.
Please check for consistency and ability to merge.

Dutch translation for 2.3.0.

---

lang/xca_ja.ts

In preparation for the release on April 17, we added Japanese translation and minor changes.
Please check for consistency and ability to merge.

Japanese translation for 2.3.0.

---

misc/eku.text
misc/oids.text

add Adobe PDF Signing and Microsoft Office Signing OID/EKU

add document signing

---

lang/xca_hr.ts

Please find Croatian translation for XCA 2.4.0

Croatian translation for 2.4.0

---

misc/oids.text

Support Microsoft Bitlocker (Update 1of2-oids.text)

---

misc/eku.text

Support Microsoft Bitlocker (Update 2of2-eku.text)

---

lib/arguments.cpp

Fix new/delete mismatch

---

lib/digest.cpp
lib/digest.h
lib/pki_crl.h
widgets/NewCrl.cpp

Closes #312
Additionally enables usage of crlNumber set by user.

Enable usage of hashAlgo digest selected by user for CRL sign

---

doc/conf.py.in

Sphinx error:
master file /home/parallels/xca-2.4.0/doc/sphinx/contents.rst not found

Bugfix: contents.rst not found

---

lang/xca_fa.ts

This pull request contains translation of XCA to Persian. I think this translation needs some improvement of course and feedback from end users. By the way, some features and windows need to redesign in order to accept RTL UI arrangement in the future.
Thanks.

Add Persian(Iran) translation .ts file to XCA.

---

lib/pkcs11.cpp
lib/pki_scard.cpp

Also, use proper defines instead of EC one

Fix OpenSSL 3 compatibility in ED25519 smartcard code

---

lib/pki_scard.cpp

Treat CKA_ID as byte array, not Bignum

---

lang/xca_fa.ts

Would you please to verify and accept my new translations for Persian?

#451: Update Persian(Iran) translation .ts file to XCA.

---

lang/xca_BG.ts

Hello Christian,
This is the Bulgarian language support for the XCA. Thank you.
For more details, check the email too.

Bulgarian language support / XCA

---

lang/xca_nl.ts

Dutch Translation for XCA 2.5.0

---

lang/xca_id.ts
misc/xca.desktop

* Update Indonesian translation in lang/xca_id.ts
* Add Indonesian explanation in misc/xca.desktop

Updated Indonesian translation

---

lang/xca_nl.ts

Dutch Translation for XCA 2.6.0

Dutch Translation for XCA 2.6.0

---

lang/xca_hr.ts

Updated Croatian translation for 2.6.0

Updated Croatian translation for 2.6.0

---

lang/xca_it.ts
misc/xca.desktop

Updated italian translation in xca_it.ts and xca.desktop

Italian translation for 2.6 release

---

lang/xca_de.ts

I fixed some smaller german typos.

Fixed german typos

---

lang/xca_fa.ts

Based on calling for update translators, Persian translations has been updated.

Updating Persian translations due to call for update

---

lang/xca_nl.ts

Dutch Translation for XCA 2.7.0 (2nd try)

Dutch Translation for XCA 2.7.0

---

lang/xca_bg.ts

Christian, thank you for the time along the additional QT platform language tool-specific suggestions. It helps improve my understanding on the workflows for maintaining the XCA UI BG language strings.

BG lang UI update
